adapters:
  135:
    url: https://client.135.by/api/geo/prices
  107:
    url: https://taxi107-minsk.hivelogin.ru/api/client/web/1.0/order/estimate
  yandex:
    url: sf

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxi_application
    username: root
    password: 1111
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
